### ISSUE TITLE
Doesnt do any searches, just closes.

### ISSUE THREAD

**Issue by Wasfgsd** [TheNetsky/Microsoft-Rewards-Script#159]
![Screenshot 2024-10-08 223635](https://github.com/user-attachments/assets/da874390-a9d9-4af8-974d-37c43eb361f1)
The program closes as soon as it logs in and gets to the reward page, these are my settings in .config. I tried uninstalling/deleting the program and rebuilding it, but it does the same thing.
![image](https://github.com/user-attachments/assets/2061b7a0-1aea-4f52-afba-747ee04f0bc4)

**Comment by Wasfgsd** [comment]
Even trying older builds that worked no longer work, I'm unsure what's gone wrong.

**Comment by devallareddyb** [comment]
> Even trying older builds that worked, going into the appdata/local folder and deleting any cache and playwright files and it still no longer works, I'm unsure what's gone wrong.

Disable puchcards, it should work

**Comment by devallareddyb** [comment]
May be this can help if you update Workers.ts

// Punch Card
async doPunchCard(page: Page, data: DashboardData) {
    // Filter uncompleted punch cards, ensuring parentPromotion exists
    const punchCardsUncompleted = data.punchCards?.filter(x => x.parentPromotion && !x.parentPromotion.complete) ?? [];

    if (!punchCardsUncompleted.length) {
        this.bot.log('PUNCH-CARD', 'All "Punch Cards" have already been completed');
        return;
    }

    for (const punchCard of punchCardsUncompleted) {
        // Ensure parentPromotion exists before proceeding
        if (!punchCard.parentPromotion) {
            this.bot.log('PUNCH-CARD', 'Skipping punchcard: Parent promotion is missing or null');
            continue; // Skip this punch card
        }

        // Get latest page for each card
        page = await this.bot.browser.utils.getLatestTab(page);

        const activitiesUncompleted = punchCard.childPromotions.filter(x => !x.complete); // Only return uncompleted activities

        // Solve Activities
        this.bot.log('PUNCH-CARD', `Started solving "Punch Card" items for punchcard: "${punchCard.parentPromotion.title}"`);

        // Go to punch card index page in a new tab
        await page.goto(punchCard.parentPromotion.destinationUrl, { referer: this.bot.config.baseURL });

        // Wait for new page to load, max 10 seconds, however try regardless in case of error
        await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});

        await this.solveActivities(page, activitiesUncompleted, punchCard);

        page = await this.bot.browser.utils.getLatestTab(page);

        const pages = page.context().pages();

        if (pages.length > 3) {
            await page.close();
        } else {
            await this.bot.browser.func.goHome(page);
        }

        this.bot.log('PUNCH-CARD', `All items for punchcard: "${punchCard.parentPromotion.title}" have been completed`);
    }

    this.bot.log('PUNCH-CARD', 'All "Punch Card" items have been completed');
}

**Comment by TheNetsky** [comment]
Never seen this happen before, but I will add a check for it, most likely exactly as given above.

**Comment by Wasfgsd** [comment]
> > Even trying older builds that worked, going into the appdata/local folder and deleting any cache and playwright files and it still no longer works, I'm unsure what's gone wrong.
> 
> Disable puchcards, it should work

Disabling punchcards worked, thanks! I tried your code below and deleted/rebuilt the program but it still had the same problem so I'm not sure if I did it correctly or what but at least for now running without the punchcards works!

**Comment by TheNetsky** [comment]
For those having issues, feel free to try https://github.com/TheNetsky/Microsoft-Rewards-Script/tree/1.4.12

**Comment by Wasfgsd** [comment]
> For those having issues, feel free to try https://github.com/TheNetsky/Microsoft-Rewards-Script/tree/1.4.12

Version 1.4.12 gives these errors when trying to build
![Screenshot 2024-10-12 181840](https://github.com/user-attachments/assets/30665651-9f5d-47e0-9d77-4d02201aada6)

**Comment by TheNetsky** [comment]
I cannot replicate that, try removing the lines and see if that works

**Comment by Titaniumtown** [comment]
I can reproduce this issue. I'm on nixOS

**Comment by TheNetsky** [comment]
Fixed in 1.4.12 branch

**Comment by Titaniumtown** [comment]
@TheNetsky why is it in a separate branch and not in master with releases being tagged?

**Comment by TheNetsky** [comment]
Because I'm testing out a new playwright lib, and don't want to push that yet until it's tested a bit more, also testing to do Desktop and Mobile searches in parallel

**Comment by Titaniumtown** [comment]
@mdunzik can you run `git branch` to ensure you're on the correct branch?

**Comment by mdunzik** [comment]
Just re-cloned the git repository and ran it and still having the same issue. I'm on the main branch.
![Uploading Screenshot_20241016_205419.png…]()

**Comment by Titaniumtown** [comment]
Was there a deleted comment? I got notifs for this issue.

**Comment by mdunzik** [comment]
With the 1.4.12 branch I'm no longer getting the punch card error, but instead this different one. 
![Screenshot_20241016_211012](https://github.com/user-attachments/assets/71d806bf-fdf9-4e5f-b82c-0e0eb6b84bbc)

**Comment by TheNetsky** [comment]
Fixed in .12
